### ISSUE TITLE
Feature Request: Add async function and documentation

### ISSUE THREAD

**Issue by personjs** [Arkanic/rtljs#1]
Would it be possible to add a `readAsync` function, or can that be achieved by looping through the `readSync` function? If so, can examples be added for this and possibly processing the returned data?

**Comment by Arkanic** [comment]
definitely possible, infact the library actually has an async function
however i've not been able to [get it to work](https://github.com/Arkanic/rtljs/blob/04d4b71debdcc771edd4867d89273a680a701bc7/src/rtlsdr-device.ts#L494)

I think your best bet would be having some sort of seperate thread/setInterval that just reads x amount of data and repeats
I'm a bit busy at the moment, but at some point ill look over the code again and try and fix some issues (including getting that async to work)

Sorry for the hassle

**Comment by Arkanic** [comment]
just added async to the package now, just update it
async callback works now, but the issue is that cancelAsync does not work for some reason that i have been banging my head around about

hope this helps

**Comment by personjs** [comment]
you are the best! thank you!

**Comment by Arkanic** [comment]
works so long as you dont want to turn it off :^)

**Comment by Arkanic** [comment]
forgot to put it in the examples but if the program hangs for some reason it is probably because you forgot to use device.resetBuffer() before reading data
